/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#cc97ff',
        'primary-dim': '#9c48ea',
        'primary-container': '#2d1a4e',
        'on-primary': '#1a0030',
        'on-primary-container': '#e8d5ff',
        secondary: '#d8e3fb',
        'secondary-container': '#1e2a3e',
        'on-secondary-container': '#c0cfeb',
        tertiary: '#ff95a0',
        'tertiary-container': '#3e1a1e',
        error: '#ff6e84',
        'error-container': '#3e1a20',
        surface: '#0e0e0e',
        'surface-dim': '#0a0a0a',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191919',
        'surface-container-high': '#1f1f1f',
        'surface-container-highest': '#262626',
        'on-surface': '#ffffff',
        'on-surface-variant': '#ababab',
        outline: '#484848',
        'outline-variant': '#333333',
        'inverse-surface': '#e6e6e6',
        'inverse-on-surface': '#1a1a1a',
        'inverse-primary': '#6a3ea1',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'Segoe UI', 'sans-serif'],
        body: ['Inter', 'Segoe UI', 'sans-serif'],
        label: ['Space Grotesk', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
